services:
  webapp:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: rise-gent-gr08
    container_name: rise8-webapp
    ports:
      - "80:8080"
    networks:
      - app-network
    volumes:
      - ./appsettings.json:/App/appsettings.json

networks:
  app-network:
    driver: bridge

volumes:
  rise_data:
  # rise_secrets: