services:
  webapp:
    image: rise-gent-gr08
    container_name: rise8-webapp
    restart: always
    ports:
      - "80:8080"
    networks:
      - app-network
    volumes:
      - ./appsettings.json:/App/appsettings.json
      - /home/rise8-user/data/app-logs/log-20241217.log:/App/logs/log-20241217.log

networks:
  app-network:
    driver: bridge

volumes:
  rise_data:
  app-logs:
