pipeline {
    agent { label "app" }

    environment {
        CONTAINER_NAME="rise8-webapp"
        CONTAINER_IMAGE="rise-gent-gr08"
        DISCORD_WEBHOOK_URL= credentials('dotnet_discord_webhook')
    }
    stages {
        stage('Preparation') {
            steps {
                script {
                    echo "Checking for running Docker containers"

                    def containerExists = sh(
                        script: "docker ps -a -q -f name=${CONTAINER_NAME}",
                        returnStdout: true
                    ).trim()

                    if (containerExists) {
                        echo "Container ${CONTAINER_NAME} is running. Stopping and removing it..."
                        sh "docker stop ${CONTAINER_NAME}"
                        sh "docker rm ${CONTAINER_NAME}"
                        sh "docker rmi ${CONTAINER_IMAGE}"
                        sh "docker system prune -a -f"
                    } else {
                        echo "No running container named ${CONTAINER_NAME} found."
                    }
                }
            }
        }
        stage('Test'){
            steps {
                echo "Running Domain Tests"
                dir("Rise.Domain.Tests/") {
                    sh "dotnet test"
                }

                // echo "Running Client Tests"
                // dir("Rise.Client.Tests/") {
                //     sh "dotnet test"
                // }
            }


        }

        stage('Build'){
            steps {
                echo "Starting Docker Compose services..."
                dir("docker/") {
                    sh "docker compose up -d"
                }
            }
        }
    }

    post {
        always {
            discordSend (
                title: "${env.JOB_NAME} #${env.BUILD_NUMBER}",
                description:"**Build:** ${env.BUILD_NUMBER}\n**Status:** ${currentBuild.currentResult}\n**Node_name:** ${env.NODE_NAME}\n\n**Website:** [360zorg-gent8.vichogent.be](https://360zorg-gent8.vichogent.be)\n**Commit:** ${env.GIT_COMMIT}\n**Branch:** ${env.GIT_BRANCH}",
                link: env.BUILD_URL,
                result: currentBuild.currentResult,
                //enableArtifactsList: true,
                //showChangeset: true,
                webhookURL: "${DISCORD_WEBHOOK_URL}"
            )

        }
    }
}   
