pipeline {
    agent { label "app" }

    environment {
        CONTAINER_NAME="rise8-webapp"
        CONTAINER_IMAGE="rise-gent-gr08"
        DISCORD_WEBHOOK_URL= credentials('dotnet_discord_webhook')
    }
    stages {
        stage('Test'){
            steps {
                echo "Running Domain Tests"
                dir("Rise.Domain.Tests/") {
                    sh "dotnet test"
                }

                // echo "Running Client Tests"
                // dir("Rise.Client.Tests/") {
                //     sh "dotnet test"
                // }
            }
        }

        stage('Build'){
            steps {
                echo "Building Docker image..."
                dir("docker/") {
                    sh "docker build -t ${CONTAINER_IMAGE} -f Dockerfile ../"
                }
            }
        }

        stage('Restart Container'){
            steps {
                echo "Restart Docker container ${CONTAINER_NAME}"
                sh "docker restart ${CONTAINER_NAME}"
            }
        }

        stage('Prune Build Cache'){
            steps {
                echo "Prune Docker builder cache"
                sh "docker builder prune -f"
            }
        }
    }

    post {
        always {
            discordSend (
                title: "${env.JOB_NAME} #${env.BUILD_NUMBER}",
                description:"**Build:** ${env.BUILD_NUMBER}\n**Status:** ${currentBuild.currentResult}\n**Node_name:** ${env.NODE_NAME}\n\n**Website:** [360zorg-gent8.vichogent.be](https://360zorg-gent8.vichogent.be)\n**Commit:** ${env.GIT_COMMIT}\n**Branch:** ${env.GIT_BRANCH}",
                link: env.BUILD_URL,
                result: currentBuild.currentResult,
                //enableArtifactsList: true,
                //showChangeset: true,
                webhookURL: "${DISCORD_WEBHOOK_URL}"
            )

        }
    }
}
